# Generated by Django 4.2.6 on 2023-11-02 05:07

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shortDescription', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[\\w\\s\\-]+$', message='Short description can only have word characters such as letters (a-z, A-Z), digits (0-9),underscores (_), whitespace, and hyphens')])),
                ('price', models.TextField(validators=[django.core.validators.RegexValidator('^\\d+\\.\\d{2}$', message='The price amount should be written whole digits followed by 2 decimal places. Example: 6.49')])),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retailer', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^\\S+$', message='The name of the retailer should be non-whitespace at the beginnng and at the end. Example: target')])),
                ('purchaseDate', models.DateField(validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}-\\d{2}$', message='Purchase date should have a format YYYY-MM-DD')])),
                ('purchaseTime', models.TimeField(validators=[django.core.validators.RegexValidator('^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$', message='Purchase time should have a format HH:MM')])),
                ('total', models.TextField(validators=[django.core.validators.RegexValidator('^\\d+\\.\\d{2}$', message='The price amount should be written whole digits followed by 2 decimal places. Example: 6.49')])),
                ('items', models.ManyToManyField(to='receipt_api.item')),
            ],
        ),
    ]
